[workspace]
members = [".", "derive"]

[package]
name = "kfl"
version = "0.4.0"
edition = "2024"
description = "Another KDL language implementation"
license = "MIT/Apache-2.0"
keywords = ["kdl", "configuration", "parser"]
categories = ["parsing", "parser-implementations", "config", "encoding"]
homepage = "https://gitlab.com/synthetic/kfl/kfl"
documentation = "https://docs.rs/kfl"
rust-version = "1.85.0"
readme = "README.md"

[dependencies]
kfl-derive = { path = "./derive", version = "0", optional = true }
chumsky = { version = "1.0.0-alpha.7" }
thiserror = "1"
miette = "7"

# optional

base64 = { version = "0.22", optional = true }
chrono = { version = "0.4", optional = true }
http = { version = "1", optional = true }
minicbor = { version = "0.24", optional = true, features = ["std", "derive"] }
unicode-width = { version = "0.1", optional = true }

[dev-dependencies]
miette = { version = "7", features = ["fancy"] }

# TODO remove

assert-json-diff = "2"
serde_json = "1"

[features]
default = ["std", "derive", "base64", "line-numbers"]
derive = ["dep:kfl-derive"]
base64 = ["dep:base64"]
line-numbers = ["dep:unicode-width"]
std = []
